#!/bin/bash

#https://adbird.hatenablog.com/entry/2016/12/20/024747

pandoc $1 -s -f markdown -t html5 -c ~/dotfiles/pandoc/light.css -o tmp.html
wkhtmltopdf --enable-local-file-access --margin-top 20 --margin-left 25 --margin-right 25 --margin-bottom 20 --footer-center '[page]/[topage]' tmp.html main.pdf
